name: Env Variables
on: [push]
jobs:
  example:
    runs-on: [ubuntu-latest]
    env:
      input: environment variable
    steps:
    # use env variable as input
    - uses: apolinar/hello-world-javascript-action@master
      with:
          who-to-greet: ${{ env.input }}
    
    # use input from default environement variable, change _ to .
    # our documentation suggests that env variables with _ should work
    # https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables
    
    - uses: apolinar/hello-world-javascript-action@master
      with:
          who-to-greet: ${{ hello apolinar.repository }} # GITHUB_REPOSITORY does not work but according to our docs it should

    - uses: apolinar/hello-world-javascript-action@master
      with:
          who-to-greet: ${{ github.ref }} # same thing for GITHUB_REF
          
    - uses: actions/hello-world-javascript-action@master
      with:
          who-to-greet: ${{ GITHUB.WORKSPACE }} 
    
    # weird case that works
    - uses: apolinar/hello-world-javascript-action@master
      with:
          who-to-greet: Test input - ${{ GITHUB.APOLINAR_PATH }}
    
    # this does not work
    - uses: actions/hello-world-javascript-action@master
      with:
          who-to-greet: Test input - ${{ GITHUB.APOLINAR.PATH }} 
